function out1 = dyn_eqn_quad(x_s1,x_s2,x_s3,x_s4,x_s5,v_s1,v_s2,v_s3,v_s4,v_s5,F_l1,F_l2,F_l3,g,l_p,m_p,m_q)
%DYN_EQN_QUAD
%    OUT1 = DYN_EQN_QUAD(X_S1,X_S2,X_S3,X_S4,X_S5,V_S1,V_S2,V_S3,V_S4,V_S5,F_L1,F_L2,F_L3,G,L_P,M_P,M_Q)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    03-Sep-2022 18:10:28

t2 = cos(x_s4);
t3 = cos(x_s5);
t4 = sin(x_s4);
t5 = sin(x_s5);
t6 = m_p+m_q;
t7 = v_s4.^2;
t8 = v_s5.^2;
t9 = 1.0./t6;
out1 = [-t9.*(-F_l1+l_p.*m_p.*t3.*t4.*t7+l_p.*m_p.*t3.*t4.*t8+l_p.*m_p.*t2.*t5.*v_s4.*v_s5.*2.0);t9.*(F_l2+l_p.*m_p.*t5.*t8);-t9.*(-F_l3+g.*m_p+g.*m_q+l_p.*m_p.*t2.*t3.*t7+l_p.*m_p.*t2.*t3.*t8-l_p.*m_p.*t4.*t5.*v_s4.*v_s5.*2.0)];
